# Generated by Django 5.2.16 on 2026-07-26 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSettings',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(default='Tambula Mengo', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=500, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('goal_amount', models.BigIntegerField()),
                ('event_date', models.DateField()),
                ('event_details', models.TextField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign Settings',
                'verbose_name_plural': 'Campaign Settings',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.BigIntegerField()),
                ('size_options', models.JSONField(default=list)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('donation', 'Donation'), ('kit_purchase', 'Kit Purchase')], max_length=50)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('payment_method', models.CharField(choices=[('mtn_momo', 'MTN MoMo'), ('airtel_money', 'Airtel Money'), ('bank', 'Bank Transfer'), ('card', 'Bank Card')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('internal_reference', models.CharField(max_length=255, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('donor_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.donor')),
            ],
        ),
        migrations.CreateModel(
            name='KitOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.BigIntegerField()),
                ('fulfillment_status', models.CharField(default='ordered', max_length=50)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_by', models.CharField(blank=True, max_length=255, null=True)),
                ('kit_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.kitproduct')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.transaction')),
            ],
        ),
    ]
