# Generated by Django 5.2.16 on 2026-08-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_kit_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsettings',
            name='offline_amount',
            field=models.BigIntegerField(default=0, help_text='Pre-collected / offline donations to add to the fundraising total (UGX)'),
        ),
    ]
