# Generated by Django 5.2.16 on 2026-08-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_offline_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsettings',
            name='show_leaderboard_amounts',
            field=models.BooleanField(default=True, help_text='Show total amount donated on the public donor leaderboard'),
        ),
    ]
