# Generated by Django 5.2.16 on 2026-08-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_campaignsettings_show_leaderboard_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitproduct',
            name='charge_price',
            field=models.BigIntegerField(default=24000, help_text='Actual base price charged during payment collection (UGX) — configurable in Django Admin only'),
        ),
        migrations.AlterField(
            model_name='kitproduct',
            name='price',
            field=models.BigIntegerField(help_text='Display price shown on public website (UGX)'),
        ),
    ]
